-- ============================================================
-- KINVINS.CD — PHASE 9
-- Bannières administrables via Supabase + Storage
-- ============================================================

create table if not exists public.site_banners (
  id bigint generated by default as identity primary key,
  name text not null,
  zone text not null,
  title text,
  subtitle text,
  button_label text,
  button_link text,
  image_url text,
  mobile_image_url text,
  fallback_tone text default '#5c1623',
  text_align text not null default 'left'
    check (text_align in ('left','center','right')),
  overlay integer not null default 0
    check (overlay >= 0 and overlay <= 80),
  sort_order integer not null default 0,
  active boolean not null default true,
  start_date date,
  end_date date,
  alt_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_banners enable row level security;

revoke all on table public.site_banners from anon, authenticated;
grant select on table public.site_banners to anon, authenticated;
grant insert, update, delete on table public.site_banners to authenticated;

do $$
declare seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.site_banners','id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end
$$;

-- Public : lecture des bannières actives.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='site_banners'
      and policyname='site_banners_public_read_active'
  ) then
    create policy "site_banners_public_read_active"
    on public.site_banners
    for select
    to anon, authenticated
    using (active = true);
  end if;
end
$$;

-- Admin : lecture complète.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='site_banners'
      and policyname='site_banners_admin_read_all'
  ) then
    create policy "site_banners_admin_read_all"
    on public.site_banners
    for select
    to authenticated
    using (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='site_banners'
      and policyname='site_banners_admin_insert'
  ) then
    create policy "site_banners_admin_insert"
    on public.site_banners
    for insert
    to authenticated
    with check (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='site_banners'
      and policyname='site_banners_admin_update'
  ) then
    create policy "site_banners_admin_update"
    on public.site_banners
    for update
    to authenticated
    using (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='site_banners'
      and policyname='site_banners_admin_delete'
  ) then
    create policy "site_banners_admin_delete"
    on public.site_banners
    for delete
    to authenticated
    using (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Seed du visuel principal si aucun visuel home_visual n'existe.
insert into public.site_banners (
  name,zone,title,subtitle,button_label,button_link,
  image_url,mobile_image_url,fallback_tone,text_align,overlay,
  sort_order,active,start_date,end_date,alt_text
)
select
  'Accueil — Visuel principal',
  'home_visual',
  null,null,null,null,
  'assets/images/banners/home-hero-desktop.webp',
  null,
  '#5c1623','left',0,
  1,true,null,null,
  'Bar premium à Kinshasa — KIN Vins & Spiritueux'
where not exists (
  select 1 from public.site_banners where zone='home_visual'
);

-- Bucket public destiné aux bannières.
insert into storage.buckets (
  id,name,public,file_size_limit,allowed_mime_types
)
values (
  'site-banners',
  'site-banners',
  true,
  700000,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public=excluded.public,
    file_size_limit=excluded.file_size_limit,
    allowed_mime_types=excluded.allowed_mime_types;

-- Storage : écritures uniquement admin/super_admin.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_banners_admin_select'
  ) then
    create policy "site_banners_admin_select"
    on storage.objects for select to authenticated
    using (
      bucket_id='site-banners'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_banners_admin_insert'
  ) then
    create policy "site_banners_admin_insert"
    on storage.objects for insert to authenticated
    with check (
      bucket_id='site-banners'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_banners_admin_update'
  ) then
    create policy "site_banners_admin_update"
    on storage.objects for update to authenticated
    using (
      bucket_id='site-banners'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      bucket_id='site-banners'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_banners_admin_delete'
  ) then
    create policy "site_banners_admin_delete"
    on storage.objects for delete to authenticated
    using (
      bucket_id='site-banners'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;
