-- ============================================================
-- KINVINS.CD — PHASE 10
-- Catégories d'accueil administrables
-- ============================================================

create table if not exists public.site_categories (
  id bigint generated by default as identity primary key,
  category_key text not null unique,
  number_label text,
  title text not null,
  subtitle text,
  link_url text not null default 'catalogue.html',
  image_url text,
  alt_text text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_categories enable row level security;

revoke all on table public.site_categories from anon, authenticated;
grant select on table public.site_categories to anon, authenticated;
grant insert, update, delete on table public.site_categories to authenticated;

do $$
declare seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.site_categories','id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='site_categories'
      and policyname='site_categories_public_read_active'
  ) then
    create policy "site_categories_public_read_active"
    on public.site_categories
    for select
    to anon, authenticated
    using (active=true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='site_categories'
      and policyname='site_categories_admin_read_all'
  ) then
    create policy "site_categories_admin_read_all"
    on public.site_categories
    for select
    to authenticated
    using (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='site_categories'
      and policyname='site_categories_admin_update'
  ) then
    create policy "site_categories_admin_update"
    on public.site_categories
    for update
    to authenticated
    using (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      exists (
        select 1 from public.profiles p
        where p.id=auth.uid()
          and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Seed / synchronise les 6 catégories fixes.
insert into public.site_categories
(category_key,number_label,title,subtitle,link_url,image_url,alt_text,sort_order,active)
values
('vins','01','Vins','Rouges, blancs, rosés','catalogue.html?category=Vins','/assets/images/categories/vins.webp','Vins rouges, blancs et rosés',1,true),
('champagnes','02','Champagnes','Brut, rosé, millésimé','catalogue.html?category=Champagnes','/assets/images/categories/champagnes.webp','Champagnes brut, rosé et millésimé',2,true),
('whiskies','03','Whiskies','Scotch, bourbon, single malt','catalogue.html?category=Whiskies','/assets/images/categories/whiskies.webp','Whiskies scotch, bourbon et single malt',3,true),
('cognacs','04','Cognacs','VS, VSOP, XO','catalogue.html?category=Cognacs','/assets/images/categories/cognacs.webp','Cognacs VS, VSOP et XO',4,true),
('rhums','05','Rhums','Blancs, ambrés, vieux','catalogue.html?category=Rhums','/assets/images/categories/rhums.webp','Rhums blancs, ambrés et vieux',5,true),
('coffrets','06','Coffrets','Cadeaux & éditions premium','catalogue.html?category=Coffrets','/assets/images/categories/coffrets.webp','Coffrets cadeaux et éditions premium',6,true)
on conflict (category_key) do update set
  number_label=excluded.number_label,
  title=excluded.title,
  subtitle=excluded.subtitle,
  link_url=excluded.link_url,
  image_url=coalesce(public.site_categories.image_url,excluded.image_url),
  alt_text=excluded.alt_text,
  sort_order=excluded.sort_order;

-- Bucket public des images de catégorie
insert into storage.buckets
(id,name,public,file_size_limit,allowed_mime_types)
values
('category-images','category-images',true,700000,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

-- Storage policies
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='category_images_admin_insert'
  ) then
    create policy "category_images_admin_insert"
    on storage.objects for insert to authenticated
    with check (
      bucket_id='category-images'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='category_images_admin_select'
  ) then
    create policy "category_images_admin_select"
    on storage.objects for select to authenticated
    using (
      bucket_id='category-images'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='category_images_admin_update'
  ) then
    create policy "category_images_admin_update"
    on storage.objects for update to authenticated
    using (
      bucket_id='category-images'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      bucket_id='category-images'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='category_images_admin_delete'
  ) then
    create policy "category_images_admin_delete"
    on storage.objects for delete to authenticated
    using (
      bucket_id='category-images'
      and exists (
        select 1 from public.profiles p
        where p.id=auth.uid() and p.status='active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;
