-- ============================================================
-- KINVINS.CD — PHASE 2 : PRODUITS + STOCK
-- ============================================================

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text,
  subcategory text,
  sku text unique,
  origin text,
  volume text,
  abv text,
  price numeric(12,2) not null default 0 check (price >= 0),
  promo_price numeric(12,2) check (promo_price is null or promo_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  badge text,
  description text,
  active boolean not null default true,
  featured boolean not null default false,
  image_url text,
  tone text default '#5c1e26',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Principe du moindre privilège :
-- le public lit uniquement ; seuls les utilisateurs authentifiés peuvent
-- tenter les écritures, qui restent ensuite filtrées par les politiques RLS.
revoke all on table public.products from anon, authenticated;
grant select on table public.products to anon, authenticated;
grant insert, update, delete on table public.products to authenticated;

-- Autoriser la génération de l'ID seulement pour les utilisateurs authentifiés.
do $$
declare
  seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.products', 'id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end
$$;


-- Public : lecture des produits actifs uniquement.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='products'
      and policyname='products_public_read_active'
  ) then
    create policy "products_public_read_active"
    on public.products
    for select
    to anon, authenticated
    using (active = true);
  end if;
end
$$;

-- Admin : lecture de tous les produits.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='products'
      and policyname='products_admin_read_all'
  ) then
    create policy "products_admin_read_all"
    on public.products
    for select
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : création.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='products'
      and policyname='products_admin_insert'
  ) then
    create policy "products_admin_insert"
    on public.products
    for insert
    to authenticated
    with check (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : modification.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='products'
      and policyname='products_admin_update'
  ) then
    create policy "products_admin_update"
    on public.products
    for update
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : suppression.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='products'
      and policyname='products_admin_delete'
  ) then
    create policy "products_admin_delete"
    on public.products
    for delete
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Données de départ uniquement si la table est vide.
insert into public.products
(name, category, subcategory, origin, volume, price, badge, tone, stock, description, abv, featured)
select * from (
  values
  ('Château Les Terrasses','Vins','Rouge','France','75 cl',29.00,'Sélection','#5c1e26',34,'Vin rouge élégant aux notes de fruits noirs, épices douces et finale soyeuse.','13.5%',true),
  ('Champagne Brut Impérial','Champagnes','Brut','France','75 cl',68.00,'Best seller','#6f602e',18,'Champagne brut équilibré, bulles fines, agrumes et brioche.','12%',true),
  ('Single Malt 12 Years','Whiskies','Single Malt','Écosse','70 cl',56.00,'12 ans','#855721',12,'Single malt rond et boisé, notes de miel, vanille et fruits secs.','40%',true),
  ('Cognac VSOP Réserve','Cognacs','VSOP','France','70 cl',64.00,'VSOP','#6d2b18',9,'Cognac souple et complexe, fruits confits, chêne et épices.','40%',false),
  ('Rosé Méditerranée','Vins','Rosé','France','75 cl',26.00,'Nouveau','#a35862',28,'Rosé frais et fruité, idéal à l''apéritif et avec des plats légers.','12.5%',false),
  ('Blanc Réserve','Vins','Blanc','Afrique du Sud','75 cl',24.00,'Frais','#81703a',22,'Blanc vif aux notes d''agrumes et de fruits tropicaux.','13%',false),
  ('Brut Rosé','Champagnes','Rosé','France','75 cl',72.00,'Premium','#805157',14,'Champagne rosé délicat, petits fruits rouges et finale fraîche.','12%',false),
  ('Highland Reserve','Whiskies','Blend','Écosse','70 cl',61.00,'Réserve','#6a451d',16,'Whisky équilibré, céréales toastées, caramel et bois doux.','40%',false),
  ('Dark Rum Heritage','Rhums','Ambré','Caraïbes','70 cl',39.00,'Premium','#4b2c19',21,'Rhum ambré chaleureux, vanille, caramel et épices.','40%',false),
  ('London Dry Gin','Gins','Dry','Royaume-Uni','70 cl',34.00,'Dry','#27483f',27,'Gin sec classique, genièvre, agrumes et plantes aromatiques.','43%',false),
  ('Vodka Platinum','Vodkas','Premium','Europe','70 cl',31.00,'Pure','#5d6670',30,'Vodka nette et douce, distillation multiple et texture soyeuse.','40%',false),
  ('Coffret Prestige','Coffrets','Cadeau','Sélection KIN','3 bouteilles',145.00,'Cadeau','#3c2221',8,'Coffret premium de trois bouteilles sélectionnées pour offrir.','—',false)
) as seed(name,category,subcategory,origin,volume,price,badge,tone,stock,description,abv,featured)
where not exists (select 1 from public.products);
