-- ============================================================
-- KINVINS.CD — PHASE 3
-- Import CSV/Excel + photos + Supabase Storage
-- ============================================================

-- ------------------------------------------------------------
-- 1. Galerie d'images produit
-- ------------------------------------------------------------
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  position integer not null default 1 check (position >= 1),
  is_primary boolean not null default false,
  alt_text text,
  created_at timestamptz not null default now(),
  unique (product_id, storage_path)
);

alter table public.product_images enable row level security;

revoke all on table public.product_images from anon, authenticated;
grant select on table public.product_images to anon, authenticated;
grant insert, update, delete on table public.product_images to authenticated;

do $$
declare
  seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.product_images', 'id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end
$$;

-- Lecture publique seulement pour les images de produits actifs.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='product_images'
      and policyname='product_images_public_read_active'
  ) then
    create policy "product_images_public_read_active"
    on public.product_images
    for select
    to anon, authenticated
    using (
      exists (
        select 1
        from public.products p
        where p.id = product_images.product_id
          and p.active = true
      )
    );
  end if;
end
$$;

-- Admin : lecture complète.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='product_images'
      and policyname='product_images_admin_read_all'
  ) then
    create policy "product_images_admin_read_all"
    on public.product_images
    for select
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : insert.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='product_images'
      and policyname='product_images_admin_insert'
  ) then
    create policy "product_images_admin_insert"
    on public.product_images
    for insert
    to authenticated
    with check (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : update.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='product_images'
      and policyname='product_images_admin_update'
  ) then
    create policy "product_images_admin_update"
    on public.product_images
    for update
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- Admin : delete.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='product_images'
      and policyname='product_images_admin_delete'
  ) then
    create policy "product_images_admin_delete"
    on public.product_images
    for delete
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

-- ------------------------------------------------------------
-- 2. Bucket public pour les photos du catalogue
-- Les lectures publiques sont adaptées à des images produit.
-- Les écritures restent protégées par RLS.
-- ------------------------------------------------------------
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do nothing;

-- ------------------------------------------------------------
-- 3. Storage RLS : admin/super_admin uniquement pour les écritures
-- ------------------------------------------------------------

-- SELECT requis notamment pour les uploads avec upsert.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='kin_product_images_admin_select'
  ) then
    create policy "kin_product_images_admin_select"
    on storage.objects
    for select
    to authenticated
    using (
      bucket_id = 'product-images'
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='kin_product_images_admin_insert'
  ) then
    create policy "kin_product_images_admin_insert"
    on storage.objects
    for insert
    to authenticated
    with check (
      bucket_id = 'product-images'
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='kin_product_images_admin_update'
  ) then
    create policy "kin_product_images_admin_update"
    on storage.objects
    for update
    to authenticated
    using (
      bucket_id = 'product-images'
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    )
    with check (
      bucket_id = 'product-images'
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage'
      and tablename='objects'
      and policyname='kin_product_images_admin_delete'
  ) then
    create policy "kin_product_images_admin_delete"
    on storage.objects
    for delete
    to authenticated
    using (
      bucket_id = 'product-images'
      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.status = 'active'
          and p.role in ('admin','super_admin')
      )
    );
  end if;
end
$$;
